### ISSUE TITLE
No coin production

### ISSUE THREAD

**Issue by KhafraDev** [Pseudo-Corp/SynergismOfficial#1]
- "too high taxes for C11x3 stage"
- https://discord.com/channels/677271830838640680/730669616870981674/803189614424490035

https://cdn.discordapp.com/attachments/730669616870981674/803189614407974912/Synergism-v2.1.2-2021-01-25_12_07_53.txt

**Comment by Pseudonian** [comment]
Partially fixed - coin production now works but tax spike still occurs on challenge 11

**Comment by Pseudonian** [comment]
This bug appears to have been fixed as of 174ade2
Closed until further notice. :)
