### ISSUE TITLE
Achievement 63 shouldn't check for generators

### ISSUE THREAD

**Issue by kewne7768** [Pseudo-Corp/SynergismOfficial#10]
"A careful search for Diamonds: Get 1e120,000 Coins in [Reduced Diamonds] without buying Accelerators or Boosts. "

The TS rewrite is [wrongfully checking for generators instead of accelerators/boosts](https://github.com/Pseudo-Corp/SynergismOfficial/blob/6102842f9fae82773499400f19788efa48b220e3/src/Achievements.ts#L589
). It seems that the [JS version](https://github.com/Pseudonian/SynergismOfficial/blob/70102d85dadd6d0afd85a27ed451c23374e966c9/Javascript/achievements.js#L679) never actually checked for the requirement either.

Might be better to leave this as is and just update the achievement text, shouldn't meaningfully impact game balance if players get it a bit earlier or later and it gates nothing.

**Comment by Pseudonian** [comment]
Hello Kewne,
This issue is fixed within c4759b8 !
I decided to not change the description and instead fix the check because it is intended to be unlocked only a bit later than it was currently, given that it is a 10 AP achievement.
Thank you for reporting this bug!
