### ISSUE TITLE
Loading screens don't hide the page well

### ISSUE THREAD

**Issue by nmussy** [Pseudo-Corp/SynergismOfficial#111]
The loading splash screens and offline progression recap don't cover the whole window. This is particularly visible in a portrait orientation.

## Splash screen

Before:

![image](https://user-images.githubusercontent.com/2505696/126879305-9a23d114-b582-47c7-91c7-d0707ca77c9c.png)

After:

![image](https://user-images.githubusercontent.com/2505696/126879306-eb459add-c040-4ea4-a3b0-ae9181afc9ab.png)

## Offline progress screen

Before:

![image](https://user-images.githubusercontent.com/2505696/126879321-e33da2e4-5b6c-4231-a405-6f02bd6b18d5.png)

After: 

![image](https://user-images.githubusercontent.com/2505696/126879324-82540df1-0b4f-4c32-a484-f4fdb7d2d862.png)

**Comment by strentax** [comment]
During my coding, I had this happen IF and ONLY IF there was an exception being thrown. Did you check your console log?

**Comment by nmussy** [comment]
Have you tried making the window taller than it is wide? It's especially noticeable then
