### ISSUE TITLE
Move Wow Pass v.1 on chal14 unlock.

### ISSUE THREAD

**Issue by leahiel** [Pseudo-Corp/SynergismOfficial#150]
### The Problem
Currently, Wow Pass v.1 is super far away from v.2 and v.3:
![image](https://user-images.githubusercontent.com/71794961/133541061-9b360510-2402-4c3b-88e1-2c4e7fba8ed0.png)
This was brought up in the Discord #suggestions channel, and user whippd just wrote:

![image](https://user-images.githubusercontent.com/71794961/133541172-c9ec793b-1169-4d45-9005-cd7d26774b5b.png)

So I was going to reply how to implement a way to solve this conundrum, but then I realized that would be just as pretentious as saying, "Can't they just code it to be the way I want it?" so I didn't. I've decided to write an issue instead! This is a very good problem for someone brand new to programming to solve, so I've taken efforts to outline my proposed steps to help that future lad:

### A Proposed Solution
For simplicities sake, we'll likely need to duplicate the code block containing the Wow Pass 1 in `index.html`. The duplicate should start on [line 3155](https://github.com/Pseudo-Corp/SynergismOfficial/blob/b344e60b1cf1103fc8f8c0cbbbe6e8957101481b/index.html#L3155). Set an id on the `div` in the original, and set the class on the `div` in the duplicate to `chal14`.

Then we'll need to program some ~~JavaScript~~ TypeScript to hide the original until Wow Pass 2/3 (`class='chal14'`) are visible.  `chal14` classed blocks become visible in the code block starting at [line 153 in src/UpdateHTML.ts](https://github.com/Pseudo-Corp/SynergismOfficial/blob/b344e60b1cf1103fc8f8c0cbbbe6e8957101481b/src/UpdateHTML.ts#L153).  Likely, we would put in the code that sets the original hidden within that `for` statement. (This code would take the format of `element.style.display = "none"`, where `element` is `document.getElementById(OURNEWID)`.

This would result in the Wow Pass S1 remaining where it is until the other two are unlocked, at which point would appear to move next to them.

### Potential Issues Relating to Proposed Solution
In theory, this seems like it would take to solve this problem, but I do not know if there is some other weird factor I am unaware of that might preclude this from working. (For instance, depending on how it is coded, duplicating the button id `seasonPassButton` may cause some issues even though one of the two code blocks would be hidden.)

Also, this may not even be a wanted change as it adds complexity to the project for very little profit.

**Comment by KhafraDev** [comment]
Ok

**Comment by 1e1000000** [comment]
Never make this to c14 unlock otherwise it will be harder to play, but moving it is fine.
In additional, Pass 3 seems unlock too early.
