### ISSUE TITLE
HTML elements/events switched in some cases.

### ISSUE THREAD

**Issue by KhafraDev** [Pseudo-Corp/SynergismOfficial#3]
- https://discord.com/channels/677271830838640680/730669616870981674/803036354605875261
- https://discord.com/channels/677271830838640680/730669616870981674/803015580755689482 (3rd point)

**Comment by Pseudonian** [comment]
Closed for now. This was fixed in https://github.com/Pseudo-Corp/SynergismOfficial/commit/d44427ca5bbd669b388ca358a2ab4cae8fe1d0d1
