### ISSUE TITLE
Auto-tesseract building buttons appear, despite not being unlocked.

### ISSUE THREAD

**Issue by Kappaclystic** [Pseudo-Corp/SynergismOfficial#31]
![Screenshot (10)](https://user-images.githubusercontent.com/63431093/107323959-2e927480-6a75-11eb-9b70-c5641e7ce184.png)
![Screenshot (11)](https://user-images.githubusercontent.com/63431093/107323962-2f2b0b00-6a75-11eb-81fa-60d7c58bc782.png)

I'm unsure if the autobuyers are actually functional or not; I haven't gotten far enough on the beta build to discern that yet.

**Comment by KhafraDev** [comment]
extends to upgrades as well https://discord.com/channels/677271830838640680/730669598738743306/808774441504735326

**Comment by Pseudonian** [comment]
Fixed
