### ISSUE TITLE
Interval clearing logic in importSynergism doesn't work right

### ISSUE THREAD

**Issue by kewne7768** [Pseudo-Corp/SynergismOfficial#33]
In trying to debug some time-related C15 issues in V2.1.2 (debugging the reason why 0.11s reincs give full obt for some people but not others), I noticed that the intervalHold splicing logic is broken and will result in half of the timers from the previous import remaining. This is broken in an identical way on both the TS rewrite and V2.1.2.

https://github.com/Pseudo-Corp/SynergismOfficial/blob/7137d3545dd392b03a3e0c73687ffcf3d8a1bca9/src/ImportExport.ts#L122-L137

This calls `clearInt`, which [splices](https://github.com/Pseudo-Corp/SynergismOfficial/blob/174ade20b165b2fdacc5b11c49bd6d63975797f3/src/Synergism.ts#L52-L58) the elements from the array _during_ the forEach loop. Then, forEach continues on the next array index. Because the indexes shift during the forEach and browsers implemented it stupidly, the result is that half of the elements are skipped. Then, the `.length = 0` clears the array without ever calling clearInterval on the remaining half, "leaking" the timers. The net result is that after importing a save a couple of times, `updateAll()` ends up being called much more often. This causes stuff like autobuyers and some recalculations to tick much more often than they normally would, changing the game behavior in a rather unstable but good-for-the-player way.

This is most easily tested on V2.1.2 by just running `intervalHold.forEach(clearInt);` from the console and then checking `intervalHold`. I confirmed that the TS rewrite is also broken by exporting a bunch of stuff to the `window` and messing around with it. It'll look like this (V2.1.2, Firefox 85):
![image](https://user-images.githubusercontent.com/67972089/107589123-9a0b4c00-6c05-11eb-8a17-fe3d6c768593.png)

This can be fixed in a bunch of different ways, Sets supposedly have a stable forEach (according to MDN, haven't tested if it actually is) but it's also possible to just swap that one `forEach` over to the regular browser `clearInterval` instead, because the array is cleared by hand immediately after anyway. Every other call to `clearInt` in the game is fine because it's not a loop.

**Comment by KhafraDev** [comment]
Looking over this again - I'm not sure why I chose an array over Set in the first place. So much was wrong with this implementation.

Thanks for the awesome bug hunting, should be fixed with 6c443208429661fb550c9c9ca3f1ac99addf3bb2. Was fixed in my testing but if the issue persists feel free to @ me on Discord/DMs.
