### ISSUE TITLE
Thoughts on icons

### ISSUE THREAD

**Issue by LucidCrux** [Pseudo-Corp/SynergismOfficial#343]
So the derpy graphics seem sort of a theme with this, but I was wondering what peoples' thoughts are on a "nicer" set of graphics, perhaps as an option? Don't want to step on any toes, and not for sure doing it even if people like the idea, just sort of thinking on it, as I do every time I come back to the game.

**Comment by mustache0110** [comment]
So I wonder if moving everything to a texture atlas (or whatever) is worth pursuing. Might make it easier to switch image themes, and improve loading times across the board.

But it also makes it harder to update / add individual icons. Unless it first looks at the atlas, and then 'updates' to it.

**Comment by LucidCrux** [comment]
That's up to you guys. I am stuck on a win 7 machine and can't run a compatible build process for easy testing. (No typescript / node.js experience, just raw language and html code experience with a pinch of git stuff for github). Program called "free texture packer" can combine stuff pretty easy if you want.

**Comment by LucidCrux** [comment]
submitted pull
