### ISSUE TITLE
Corruption Bugs / Visual Errors

### ISSUE THREAD

**Issue by Pseudonian** [Pseudo-Corp/SynergismOfficial#39]
1) When loading the game, corruptions display as 0/0 throughout instead of the proper level setup
https://discordapp.com/channels/677271830838640680/730669616870981674/803061866418012221
https://discordapp.com/channels/677271830838640680/730669616870981674/804731057215373362
Second link has video

2) Visual Errors on "Market Deflation" 6+. Effect seems to show 0 for all of them when this is not true.
https://discordapp.com/channels/677271830838640680/730669616870981674/806906414747353108

**Comment by KhafraDev** [comment]
#1 is fixed with 1852113dd2a8df3bd95b772acaa3771b83566832

**Comment by Pseudonian** [comment]
#2 is fixed with eb780c4
Closing for now, until new corruption bugs are discovered.
