### ISSUE TITLE
Tax spike

### ISSUE THREAD

**Issue by KhafraDev** [Pseudo-Corp/SynergismOfficial#4]
- https://cdn.discordapp.com/attachments/730669616870981674/803338019019948073/Synergism-v2.5.0alpha-1-2021-01-25_18_57_15.txt
- possible around "1e308 coins / tick" - https://discord.com/channels/677271830838640680/730669616870981674/803368688111190058

**Comment by Pseudonian** [comment]
This particular tax spike fixed - challenge 11 tax spike is not fixed (addressed in #1 ) This issue in particular fixed in #6
