### ISSUE TITLE
Ant sacrifice visible without r5x24

### ISSUE THREAD

**Issue by everyday847** [Pseudo-Corp/SynergismOfficial#47]
Whoops, submitted without content.

At least on the Kongregate version, on Chrome or Firefox on Ubuntu, the automatic ant sacrifice UI is visible but nonfunctional without the relevant research.

**Comment by Pseudonian** [comment]
Hello,
Is this a persistent bug in the testing version?

**Comment by everyday847** [comment]
By testing version do you mean a recent commit here that maybe hasn't been deployed to Kongregate? No idea; if you can give me the commit hash most recently deployed to Kongregate I can both test the current repo head and, if it happens to have been resolved incidentally, I can git bisect.

**Comment by Pseudonian** [comment]
To determine if it is a bug on the test version:
1) Come to this game link: https://pseudo-corp.github.io/SynergismOfficial/
2) Import the savefile that has this bug

Visually, it should not display ant sacrifice before it is unlocked.

**Comment by everyday847** [comment]
Yup, it's bugged at that link as well. Savefile attached.
[Synergism-v2.1.2-2021-04-04 23_13_13.txt](https://github.com/Pseudo-Corp/SynergismOfficial/files/6256108/Synergism-v2.1.2-2021-04-04.23_13_13.txt)

**Comment by blaze33** [comment]
I proposed a fix for this bug in the live version some time ago: https://github.com/Pseudonian/SynergismOfficial/pull/249 
The check to display or not the auto sacrifice buttons was accidentally removed when the checks for the display of the talisman auto enhance / fortify buttons were introduced.

To patch v2.5, pasting the same 3 lines of code in UpdateHTML.ts around line 246 should be good:

![Capture d’écran de 2021-04-12 17-21-20](https://user-images.githubusercontent.com/542233/114419290-979c8280-9bb3-11eb-840a-3af3f5aa72b5.png)

**Comment by KhafraDev** [comment]
> 
> 
> I proposed a fix for this bug in the live version some time ago: [Pseudonian/SynergismOfficial#249](https://github.com/Pseudonian/SynergismOfficial/pull/249)
> The check to display or not the auto sacrifice buttons was accidentally removed when the checks for the display of the talisman auto enhance / fortify buttons were introduced.
> 
> To patch v2.5, pasting the same 3 lines of code in UpdateHTML.ts around line 246 should be good:
> 
> ![Capture d’écran de 2021-04-12 17-21-20](https://user-images.githubusercontent.com/542233/114419290-979c8280-9bb3-11eb-840a-3af3f5aa72b5.png)

Fixed, thanks.

Live version probably won't be getting any updates until v2.5.0 is ready, unless @Pseudonian is up to it.
