### ISSUE TITLE
Entering Ascension Challenges with talisman fragments, const upgrade 9 and starting rune levels

### ISSUE THREAD

**Issue by dkolke** [Pseudo-Corp/SynergismOfficial#552]
Problem: 
When entering an ascension challenge and having constant upgrade 9 purchased, the amount of talisman fragments before entering the challenge is used. So, prism rune will give crystal upgrades higher than intended.

Order of the calls in reset.ts:

https://github.com/Pseudo-Corp/SynergismOfficial/blob/e228ab2233a590dd0c5d0ef792655f5ca25df13c/src/Reset.ts#L373
https://github.com/Pseudo-Corp/SynergismOfficial/blob/e228ab2233a590dd0c5d0ef792655f5ca25df13c/src/Reset.ts#L552

relevant part in resetUpgrades:

```
if (i > 1.5) {
    player.crystalUpgrades = [0, 0, 0, 0, 0, 0, 0, 0]
    player.crystalUpgradesCost = [7, 15, 20, 40, 100, 200, 500, 1000]

    let m = 0
    m += Math.floor(G.rune3level * G.effectiveLevelMult / 16) * 100 / 100
    if (player.upgrades[73] > 0.5 && player.currentChallenge.reincarnation !== 0) {
      m += 10
    }
    player.crystalUpgrades = [m, m, m, m, m, m, m, m]
  }
```

I dont know how the best way is to fix it, so i made this issue.

**Comment by HypertextEye** [comment]
I made a PR for this (it also fixes longstanding c15 issue)
https://github.com/Pseudo-Corp/SynergismOfficial/pull/556
